name: Build and deploy Node.js app to Azure Web App - goodvibes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build React app
        run: |
          cd my-simple-website
          npm install
          npm run build

      - name: Zip build artifact for deployment
        run: |
          cd my-simple-website/build
          zip -r ../../release.zip .

      - name: Upload build artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A1312AA7914464D9EA687AE1C20120B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B846C31774B049E2B23236BA1084119D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F41BBC6F87AE404AAFD894509E123331 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'goodvibes'
          slot-name: 'Production'
          package: ./build
